"""Extractor for protondrive-sdk TypeScript generated types (driveTypes.ts + coreTypes.ts).

These files are auto-generated by openapi-typescript from Proton's internal
OpenAPI spec. They contain:
- paths: URL → operation mapping
- components.schemas: DTO type definitions
- operations: full request/response schemas

This is the highest-fidelity source since it's machine-generated from the
canonical spec.
"""

import re
import sys
from pathlib import Path

# Project root (two levels up from this file)
PROJECT_ROOT = Path(__file__).parent.parent.parent
API_DIR = PROJECT_ROOT / "api"
SOURCES_DIR = PROJECT_ROOT / "sources"

SOURCE_NAME = "protondrive-sdk-ts"

# Patterns for parsing the openapi-typescript output
PATH_ENTRY_RE = re.compile(r'^\s+"(/[^"]+)":\s*\{')
METHOD_REF_RE = re.compile(
    r"^\s+(?:/\*\*[^*]*\*/\s+)?" r"(get|post|put|delete|patch):\s*operations\[\"([^\"]+)\"\]"
)
METHOD_NEVER_RE = re.compile(r"^\s+(get|post|put|delete|patch)\?:\s*never;")
OPERATION_ENTRY_RE = re.compile(r'^\s+"([^"]+)":\s*\{')
COMMENT_RE = re.compile(r"/\*\*\s*(.*?)\s*\*/", re.DOTALL)


def parse_paths(lines: list[str], start: int, end: int) -> dict[str, dict[str, str]]:
    """Parse the paths interface to extract URL → {method: operationId} mappings."""
    result: dict[str, dict[str, str]] = {}
    current_path = None
    brace_depth = 0

    for i in range(start, end):
        line = lines[i]

        # Track brace depth to know when we leave a path entry
        brace_depth += line.count("{") - line.count("}")

        # New path entry
        m = PATH_ENTRY_RE.match(line)
        if m and brace_depth <= 2:
            current_path = m.group(1)
            if current_path not in result:
                result[current_path] = {}
            continue

        if current_path is None:
            continue

        # Method referencing an operation
        m = METHOD_REF_RE.match(line)
        if m:
            method = m.group(1).upper()
            op_id = m.group(2)
            result[current_path][method] = op_id

    return result


def extract_path_params(path: str) -> dict[str, dict]:
    """Extract path parameters from a URL template."""
    params = {}
    for m in re.finditer(r"\{(\w+)\}", path):
        params[m.group(1)] = {"type": "string"}
    return params


def parse_operation_block(lines: list[str], start: int) -> tuple[dict, int]:
    """Parse a single operation block starting at the opening brace line.

    Returns (operation_dict, end_line_index).
    """
    op: dict = {}
    brace_depth = 0
    section = None  # 'parameters', 'requestBody', 'responses'
    response_code = None

    i = start
    while i < len(lines):
        line = lines[i]
        brace_depth += line.count("{") - line.count("}")

        if brace_depth <= 0:
            return op, i

        # Detect section transitions
        if re.match(r"\s+parameters:\s*\{", line):
            section = "parameters"
        elif re.match(r"\s+requestBody\??:\s*\{", line):
            section = "requestBody"
        elif re.match(r"\s+responses:\s*\{", line):
            section = "responses"

        # Extract path parameters
        if section == "parameters":
            path_match = re.match(r"\s+path:\s*\{", line)
            if path_match:
                # Parse path params until closing brace
                j = i + 1
                params = {}
                while j < len(lines) and "};" not in lines[j] and "}" not in lines[j].strip():
                    pm = re.match(
                        r'\s+(\w+):\s*(?:components\["schemas"\]\["(\w+)"\]|(\w+))'
                        r"(\s*\|\s*null)?;",
                        lines[j],
                    )
                    if pm:
                        param_name = pm.group(1)
                        params[param_name] = {"type": "string"}
                    j += 1
                if params:
                    op["pathParams"] = params

            # Extract query parameters
            query_match = re.match(r"\s+query\??:\s*\{", line)
            if query_match:
                j = i + 1
                qparams = {}
                while j < len(lines) and "};" not in lines[j]:
                    qm = re.match(r"\s+(\w+)\??:\s*(.+?)(?:\s*\|\s*null)?;", lines[j])
                    if qm:
                        qp_name = qm.group(1)
                        qp_type = qm.group(2).strip()
                        qparams[qp_name] = _ts_type_to_schema(qp_type)
                    j += 1
                if qparams:
                    op.setdefault("queryParams", {}).update(qparams)

        # Extract request body fields
        if section == "requestBody":
            schema_ref = re.match(
                r'\s+"application/json":\s*components\["schemas"\]\["(\w+)"\];',
                line,
            )
            if schema_ref:
                op["requestBodyRef"] = schema_ref.group(1)

        # Extract response codes and their schema refs
        if section == "responses":
            code_match = re.match(r"\s+(\d{3}):\s*\{", line)
            if code_match:
                response_code = code_match.group(1)

            if response_code:
                schema_ref = re.match(
                    r'\s+"application/json":\s*components\["schemas"\]\["(\w+)"\];',
                    line,
                )
                if schema_ref:
                    op.setdefault("responses", {})[response_code] = {
                        "schemaRef": schema_ref.group(1)
                    }

        i += 1

    return op, i


def parse_schemas(lines: list[str], start: int, end: int) -> dict[str, dict]:
    """Parse the components.schemas section into a dict of schema name → fields."""
    schemas: dict[str, dict] = {}
    current_schema = None
    current_fields: dict = {}
    brace_depth = 0
    base_depth = 0
    pending_description = None

    i = start
    while i < end:
        line = lines[i]

        # Capture JSDoc comments for descriptions
        comment_match = COMMENT_RE.search(line)
        if comment_match:
            desc_text = comment_match.group(1)
            # Extract @description tag if present
            desc_match = re.search(r"@description\s+(.+?)(?:\s*\*\/|$)", desc_text, re.DOTALL)
            if desc_match:
                pending_description = re.sub(r"\s*\*\s*", " ", desc_match.group(1)).strip()

        # New schema definition
        schema_match = re.match(r"\s{8}(\w+):\s*\{", line)
        if schema_match and brace_depth <= 2:
            if current_schema and current_fields:
                schemas[current_schema] = current_fields
            current_schema = schema_match.group(1)
            current_fields = {}
            base_depth = brace_depth
            pending_description = None

        # Simple schema (enum/constant)
        simple_match = re.match(r"\s{8}(\w+):\s*(.+);$", line)
        if simple_match and brace_depth <= 2 and not line.strip().startswith("//"):
            name = simple_match.group(1)
            value = simple_match.group(2).strip()
            if not value.startswith("{"):
                schemas[name] = _parse_simple_type(value)

        # Field within current schema
        if current_schema and brace_depth > base_depth:
            field_match = re.match(r"\s+(\w+)\??:\s*(.+?)(?:\s*\|\s*null)?;$", line)
            if field_match:
                fname = field_match.group(1)
                ftype = field_match.group(2).strip()
                field_def = _ts_type_to_schema(ftype)
                # Check for nullable
                if "| null" in line:
                    field_def["nullable"] = True
                if pending_description:
                    field_def["description"] = pending_description
                    pending_description = None
                current_fields[fname] = field_def

        brace_depth += line.count("{") - line.count("}")

        # Schema closed
        if current_schema and brace_depth <= base_depth:
            if current_fields:
                schemas[current_schema] = current_fields
            current_schema = None
            current_fields = {}

        i += 1

    if current_schema and current_fields:
        schemas[current_schema] = current_fields

    return schemas


def _parse_simple_type(value: str) -> dict:
    """Parse a simple TypeScript type value into a schema."""
    # Integer literal or enum
    if re.match(r"^\d+$", value):
        return {"type": "integer", "enum": [int(value)]}
    # String literal
    if value.startswith(('"', "'")):
        return {"type": "string", "enum": [value.strip("\"'")]}
    # Union of integers
    int_union = re.findall(r"\d+", value)
    if int_union and "|" in value:
        return {"type": "integer", "enum": [int(x) for x in int_union]}
    return {"type": "string"}


def _ts_type_to_schema(ts_type: str) -> dict:
    """Convert a TypeScript type annotation to our field schema."""
    ts_type = ts_type.strip().rstrip(";")

    # Remove nullable suffix for processing
    nullable = False
    if ts_type.endswith("| null"):
        ts_type = ts_type[: -len("| null")].strip()
        nullable = True

    result: dict = {}

    # Component reference
    ref_match = re.match(r'components\["schemas"\]\["(\w+)"\]', ts_type)
    if ref_match:
        result = {"type": "string", "description": f"$ref:{ref_match.group(1)}"}
    elif ts_type == "string":
        result = {"type": "string"}
    elif ts_type == "number":
        result = {"type": "number"}
    elif ts_type == "boolean":
        result = {"type": "boolean"}
    elif ts_type == "integer":
        result = {"type": "integer"}
    elif ts_type.endswith("[]"):
        inner = ts_type[:-2]
        result = {"type": "array", "items": _ts_type_to_schema(inner)}
    elif "|" in ts_type:
        # Union type — try to extract enum values
        parts = [p.strip() for p in ts_type.split("|")]
        int_parts = [p for p in parts if re.match(r"^\d+$", p)]
        if int_parts:
            result = {"type": "integer", "enum": [int(p) for p in int_parts]}
        else:
            result = {"type": "string"}
    else:
        result = {"type": "string"}

    if nullable:
        result["nullable"] = True

    return result


def resolve_schema_ref(ref_name: str, schemas: dict[str, dict], depth: int = 0) -> dict:
    """Resolve a schema reference into inline fields."""
    if depth > 5:
        return {"type": "object"}

    schema = schemas.get(ref_name, {})
    if not schema:
        return {"type": "object", "description": ref_name}

    # If schema has fields (is an object type), inline them
    if isinstance(schema, dict) and all(isinstance(v, dict) for v in schema.values()):
        # Check if it's a simple type (has 'type' key at top level)
        if "type" in schema:
            return schema
        # It's an object with fields
        resolved_fields = {}
        for fname, fdef in schema.items():
            if isinstance(fdef, dict):
                # Resolve nested refs
                desc = fdef.get("description", "")
                if isinstance(desc, str) and desc.startswith("$ref:"):
                    inner_ref = desc[5:]
                    resolved = resolve_schema_ref(inner_ref, schemas, depth + 1)
                    resolved_fields[fname] = resolved
                else:
                    resolved_fields[fname] = fdef
            else:
                resolved_fields[fname] = {"type": "string"}
        return {"type": "object", "fields": resolved_fields}

    return {"type": "object"}


def parse_operations(lines: list[str], start: int, end: int) -> dict[str, dict]:
    """Parse the operations interface into operation_id → operation data."""
    ops: dict[str, dict] = {}
    i = start

    while i < end:
        line = lines[i]
        m = OPERATION_ENTRY_RE.match(line)
        if m:
            op_id = m.group(1)
            op_data, end_i = parse_operation_block(lines, i)
            ops[op_id] = op_data
            i = end_i
        i += 1

    return ops


def operation_id_to_method(op_id: str) -> str:
    """Extract HTTP method from operation ID (e.g. 'post_drive-...' → 'POST')."""
    parts = op_id.split("_", 1)
    if parts:
        return parts[0].upper()
    return "GET"


def build_endpoint(
    path: str,
    methods: dict[str, str],
    operations: dict[str, dict],
    schemas: dict[str, dict],
) -> dict:
    """Build an endpoint definition from path, method→opId map, and parsed operations."""
    endpoint: dict = {
        "path": path,
        "operations": {},
    }

    path_params = extract_path_params(path)
    if path_params:
        endpoint["pathParams"] = path_params

    for method, op_id in methods.items():
        op_data = operations.get(op_id, {})
        op_def: dict = {"operationId": op_id}

        # Query params
        if "queryParams" in op_data:
            op_def["queryParams"] = op_data["queryParams"]

        # Request body
        if "requestBodyRef" in op_data:
            ref_name = op_data["requestBodyRef"]
            resolved = resolve_schema_ref(ref_name, schemas)
            if resolved.get("type") == "object" and "fields" in resolved:
                op_def["requestBody"] = {
                    "contentType": "application/json",
                    "fields": resolved["fields"],
                }
            else:
                op_def["requestBody"] = {
                    "contentType": "application/json",
                    "fields": {ref_name: {"type": "object"}},
                }

        # Responses
        if "responses" in op_data:
            op_def["responses"] = {}
            for code, resp_data in op_data["responses"].items():
                if "schemaRef" in resp_data:
                    resolved = resolve_schema_ref(resp_data["schemaRef"], schemas)
                    if resolved.get("type") == "object" and "fields" in resolved:
                        op_def["responses"][code] = {"fields": resolved["fields"]}
                    else:
                        op_def["responses"][code] = {"fields": {}}
                else:
                    op_def["responses"][code] = {"fields": {}}

        endpoint["operations"][method] = op_def

    return endpoint


def path_to_dir(path: str, service: str) -> Path:
    """Convert an API path to a directory path under api/."""
    from src.pathutil import API_DIR, normalize_path
    from src.pathutil import path_to_dir as _ptd

    return _ptd(normalize_path(path), API_DIR)


def write_endpoint(endpoint: dict, output_dir: Path) -> None:
    """Write an endpoint definition to its source file via pathutil."""
    from src.pathutil import write_endpoint as _write

    _write(endpoint.get("path", ""), endpoint.get("operations", {}), SOURCE_NAME)


def extract_file(filepath: Path, service_prefix: str) -> int:
    """Extract endpoints from a single driveTypes.ts or coreTypes.ts file."""
    content = filepath.read_text()
    lines = content.splitlines()

    # Find section boundaries
    paths_start = None
    components_start = None
    operations_start = None

    for i, line in enumerate(lines):
        if line.startswith("export interface paths {"):
            paths_start = i
        elif line.startswith("export interface components {"):
            components_start = i
        elif line.startswith("export interface operations {"):
            operations_start = i

    if paths_start is None or operations_start is None:
        print(f"  Warning: could not find expected sections in {filepath.name}")
        return 0

    # Parse sections
    schemas = {}
    if components_start is not None:
        schemas = parse_schemas(lines, components_start, operations_start)

    path_methods = parse_paths(lines, paths_start, components_start or operations_start)
    operations = parse_operations(lines, operations_start, len(lines))

    # Build and write endpoints
    count = 0
    for path, methods in path_methods.items():
        if not methods:
            continue

        endpoint = build_endpoint(path, methods, operations, schemas)

        # Determine output directory from the path
        output_dir = path_to_dir(path, service_prefix)
        write_endpoint(endpoint, output_dir)
        count += 1

    return count


def main() -> None:
    """Entry point for the protondrive-sdk TypeScript extractor."""
    sdk_dir = SOURCES_DIR / "protondrive-sdk" / "client" / "js" / "src" / "internal" / "apiService"

    if not sdk_dir.exists():
        print(f"Error: source not found at {sdk_dir}", file=sys.stderr)
        sys.exit(1)

    drive_types = sdk_dir / "driveTypes.ts"
    core_types = sdk_dir / "coreTypes.ts"

    total = 0

    if drive_types.exists():
        print(f"Extracting from {drive_types.name}...")
        count = extract_file(drive_types, "drive")
        print(f"  Extracted {count} endpoints from driveTypes.ts")
        total += count

    if core_types.exists():
        print(f"Extracting from {core_types.name}...")
        count = extract_file(core_types, "core")
        print(f"  Extracted {count} endpoints from coreTypes.ts")
        total += count

    print(f"Total: {total} endpoints extracted by {SOURCE_NAME}")


if __name__ == "__main__":
    main()
